### PR TITLE
Builder clone method

### PR DESCRIPTION
**Pull request by filipedtristao**
A clone method on Builder is useful when you need to create an instance copy with all properties defined so far, but with a different reference so the changes made to the clone do not affect the original instance and vice versa.

### CODE REVIEW

**Comment by DavidDuwaer** [comment]
Great, this `clone` method is very welcome. What if go 1 step further, and we make `Builder` completely effectively immutable? So that every public method on the `Builder` returns a a copy of the `Builder` with the change applied, instead of mutating the `Builder` itself? Then your `clone` method is called internally by every query method on the builder, but externally, the user won't have to every call a clone method.

For instance, for `Builder.where`:
```
public where(attribute: string, value: string): Builder
{
    const clone = this.clone();
    clone.query.addFilter(new FilterSpec(attribute, value));
    return clone;
}
```

Making `Builder` immutable makes the library _much_ better and behave _much_ more like users would expect (especially given most modern method-chaining libraries are immutable, for good reason). If you don't have time, then let me know and I'll try to find a moment. Though shouldn't be too much extra work from the looks of it!

**Comment by filipedtristao** [comment]
@DavidDuwaer that would be great. I created the clone method because the mutating behavior of Builder was messing up with my project.

I think i will have time to do this after tomorrow, but i wouldn't mind if you made the changes before that. :)

**Comment by filipedtristao** [comment]
@DavidDuwaer done. Can you take a look, please?

**Comment by DavidDuwaer** [comment]
Awesome, great work, thoroughly tested, nice. Will release right away, with a major version bump, as some users might have built on the mutability

**Pull request merged**
