### PR TITLE
Added possibility to call static methods in class instance

### PR DESCRIPTION
**Pull request by filipedtristao**
As with the laravel eloquent, it is interesting to have the possibility of calling Model methods both in instance and in static context.

This pull request adds this possibility.

### CODE REVIEW

**Comment by filipedtristao** [comment]
@DavidDuwaer what you thoughts about this?

I waiting for response for this PR because I have other method additions in Model class (like the `fresh()` one). If this get merged, I will make the new methods with the same structure, working in instance and static context.

**Comment by DavidDuwaer** [comment]
Can you give me a case where it would be sufficiently better to have the static methods on the objects?

Personally, I'm not convinced. In Laravel Eloquent you can do this because in PHP you can always call the static methods of a class on that class's instances, and eloquent couldn't undo that behavior if they wanted to... correct me if I'm wrong here. It doesn't make client code more brief (save for one less import statement, but that's not where briefness matters), and it brings in a PHP paradigm to the typescript world, where programmers wouldn't expect it. Also, but this may be subjective, I would argue it is confusing in Eloquent's case, as querying from your entity instance rather than from the class (or some external query service), is a bit like buying more apples from an apple, rather than the shop.

A fresh() method I'm all for! This is a method that should be on the instance and not static, and makes total sense to be there.

**Comment by filipedtristao** [comment]
About PHP, as far as I know the behavior is the same as typescript. A static method cannot be accessed directly from the instance of the class. Eloquent works with Laravel Facades, which gives the possibility that the method can be called in both static and instance context, and is a desired and programmed behavior, not a consequence of the language.

I made this PR precisely because this behavior is useful during development. For example, I work with Angular and created for my project a form base component, to help automate repetitive things like field validations and the implementation of the create and update method in the form page.

My idea was that this class would receive an instance of Coloquent and use this class to comunicate to the backend for find, create and update the resource.

For example:

```typescript
export abstract class BaseForm {

	public resource: BaseModel;

	constructor(resource: BaseModel) {
	    this.resource = resource;
	}
	
	async ngAfterContentInit() {
            this.route.params.subscribe((params) => {
                if (params.id) {
                    this.resource.find(params.id).then((response) => {
		        //Load the data here
	            });
                }
	    });
	}
	
	public create() {
	    if (this.validateForm()){
	        this.resource.save().then ...
	    }
	}
	
	public update() {
	    if (this.validateForm()){
	        this.resource.save().then ...
	    }
	}
}
```

The problem  is that my base class only has instance access, so if I want to invoke some static method (like get, find, where and etc), I have to transform this instance to the static context, which gets kind of repetitive in the code.

Another solution would be to get both the class instance and the static class in the base class constructor (which I am currently doing), but it doesn't look very pretty to me.

This is a problem that recurs in all cases where I need a generic class that should work with a coloquent resource, because within that generic class, I will need instance methods and static methods and every time i will face the same problem. Therefore the possibility of calling the methods in both contexts is very useful.

Also, I may be wrong but I believe most Coloquent users will come directly from Eloquent (which was my case) and will expect to find the same behavior in both plugins. It was one of the reasons why I adopted Coloquent for our company projects, because I want to reduce the learning curve of those coming from Laravel to Angular on our web projects.

**Comment by DavidDuwaer** [comment]
I see your point, your use case is valid and very common indeed! I need it in Eloquent too, but then I use the `.query()` method to get a builder, even though I could have started querying right on the model.

Look, all static methods are available on the instance in php:
```php
<?php
// example code

class MyClass
{
    public static function printSomething(String $something)
    {
        print $something;
    }
}

MyClass::printSomething("I can access the static method from the class\n");


$instance = new MyClass();

$instance->printSomething("I can access the static method from the instance\n");
```
You can see it running [here](https://www.tehplayground.com/P8LsX6xACMTVFlw1). It is not possible for Eloquent's builders to undo this behavior.

I suggest we take a `.query()` method too, just like in Eloquent. This way we can suit your use case, but keep I've just commited one to this PR. Would it be ok to have that, but to keep the builder method off the model instance itself?

I have no data about where users come from unfortunately! So I don't want to fully copy another library, but keep thinking independently!

**Comment by filipedtristao** [comment]
Ohh i see. I didn't know this PHP behavior, good to know.

About the `query()` method, is a very good solution for the problem, thanks!

Can we have it merged?

**Pull request merged**
