### PR TITLE
Fix for plural relations not working because of casing

### PR DESCRIPTION
**Pull request by DylandeWit**
Plural relations were not working because of camel case and kebab case.
It tries finding 'example-relation' instead exampleRelation in the model.

### CODE REVIEW

**Comment by DavidDuwaer** [comment]
Hey Dylan, thanks for contributing. Can you describe an example (or even better, since this is necessary before merging, add a test) in which your issue arises?

**Comment by DylandeWit** [comment]
Hey David, thanks for the reply. I added a test, let me know if it's okay like this.

**Comment by DavidDuwaer** [comment]
Hey Dylan,

It has been a very busy month for me, including multiple (!) vacations 😋. I finally found a moment to catch up on PRs. Again, sorry for the delay. Your PR seems alright, increasing flexibility doesn't hurt as long as it doesn't touch existing functionality, which it doesn't. I found one detail, see the commit I just did, which would prevent you from including something like 'include=some-property.itsRelation'.

Is there any specific reason you closed the PR? Do you see a problem with it?

**Comment by DylandeWit** [comment]
Hey David,
Thanks for replying. The reason I closed the PR is because I suspect this PR will break the functionality of camel cased relationship names. Correct me if I'm wrong but won't my addition always look for kebab cased relations instead of camel cased?

**Comment by DavidDuwaer** [comment]
As it looks to me, `RetrievalResponse.convertRelationNameToCamelCase` won't change relation names that are already camel cased, in which case `resourceRelationName` and `modelRelationName` in `RetrievalResponse.indexAsModel` will be the equal, making, for those cases, the functionality of that method effectively the same as before.

**Pull request merged**
