### PR TITLE
Fresh method

### PR DESCRIPTION
**Pull request by filipedtristao**
For this issue: https://github.com/DavidDuwaer/Coloquent/issues/25

### CODE REVIEW

**Comment by DavidDuwaer** [comment]
Hey there!

I notice that this creates a new & empty instance of a model. Doesn't the Eloquent version of this method reload an entity from database by its id? See [here](https://laravel.com/docs/5.8/eloquent#retrieving-models)

**Comment by filipedtristao** [comment]
Oh, my bad.

In the Eloquent, we have the following:

" The fresh method will re-retrieve the model from the database. The existing model instance will not be affected".

You think we should keep this behavior of not affecting the existing model?

**Comment by filipedtristao** [comment]
Can you take a look now?

I made the method return a new updated resource with backend data when have a id and a empty resource when doesn't.

I also added the loaded relationships of the model as include, to update the relations as well.

**Comment by DavidDuwaer** [comment]
I've changed the contract a bit; it now returns a Promise resolving to
* The reloaded model when an ID was present and a model could be found in the API
* `null` if an ID was present but the API did not find a model with that ID
* `undefined` if no ID was present on the model upon which `.refresh()` was called

**Pull request merged**
