### PR TITLE
Automatic Dates Mutation

### PR DESCRIPTION
**Pull request by milroyfraser**
this enables to do

```
class Post extends Model
{    
    protected dates = ['published_at'];
}
```
then

```
coloquentResponse.getData[0].getAttribute('published_at').toDateString() // Sun Sep 19 1982
```

### CODE REVIEW

**Comment by milroyfraser** [comment]
It would be really nice if we ca type hint `public getData(): Collection`.

**Comment by DavidDuwaer** [comment]
Many thanks for being the first contributor :).

Before we merge though I think the setAttribute side of the story should be covered too, i.e. support `setAttribute('someDate', v)` with `v` being of type `Date`, because this is what the user will be expecting if `getAttribute('someDate')` returns a `Date`.

**Comment by milroyfraser** [comment]
Thanks a lot for making this open source. It's my pleasure to contribute. 

```
    protected setAttribute(attributeName: string, value: any): void
    {
        if (value instanceof Date) {
            value = value.toISOString();
        }

        this.attributes.set(attributeName, value);
    }
```
what is your opinion on this?

**Comment by DavidDuwaer** [comment]
I'd say, to make it more predictable, change the guard
```
protected setAttribute(attributeName: string, value: any): void
{
    if (this.isDateAttribute(attributeName)) {
        value = value.toISOString();
    }

    this.attributes.set(attributeName, value);
}
```
But there is another problem: JSONAPI does not prescribe dates to be in ISO-8601 format, so this would narrow our compatibility. What if we, in the `Model.dates` array, let the user specify the format as well?
```
class Person extends Model
{    
    protected dates = {
        'lastActive': 'Y-m-d H:i:s',
        'birthdate': 'Y-m-d'
    };
}
```
As a library to parse the formatting string we can use [dateformat](https://www.npmjs.com/package/dateformat), which is pretty popular, or [php-date-formatter](https://github.com/kartik-v/php-date-formatter), which is nicer because it uses the same date syntax as PHP.

As for `moment` instead of `Date`: What Moment.js does has in itself nothing to do with what Coloquent does, and so someone who would want to use Coloquent might not want to use Moment. I think people who want their date properties to be moments should do the conversion themselves in the accessors.

**Pull request merged**
